#  print(listx[90])
#IndexError: list index out of range
try:
    listx = [1,2,3,4,5]
    print(listx[90])
except Exception as e:
    print('exception is thrown',e)
finally:
    print('always executed')
    
    
    
try: 
    # sta 1 
    # sta 2 
    # sta 3
    try:
    
    except: 
    # abnormal situation 
    # os
 
    
    
    # stat 15
except:
     # sta 16 
     try:
     except: 
         
finally:
     # sta 17
     try: 
     except:
         
    